// Objective-C API for talking to github.com/Super-NFT/wallet_mpc/client Go package.
//   gobind -lang=objc github.com/Super-NFT/wallet_mpc/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSData* _Nullable ClientGenToPk(NSString* _Nullable k1, NSString* _Nullable k2);

/**
 * Keygen
@Description: 生成私钥
 */
FOUNDATION_EXPORT NSData* _Nullable ClientKeygen(void);

FOUNDATION_EXPORT NSData* _Nullable ClientPkToGen(NSString* _Nullable privateKey);

/**
 * ReShare
@Description: reShare私钥分片
@param keyJson1 私钥分片
@param keyJson2 私钥分片
 */
FOUNDATION_EXPORT NSData* _Nullable ClientReShare(NSString* _Nullable keyJson1, NSString* _Nullable keyJson2);

/**
 * Sign
@Description: 签名
@param url 地址
@param header 请求头
@param keyJson 私钥分片
@param bz 交易信息
 */
FOUNDATION_EXPORT NSData* _Nullable ClientSign(NSString* _Nullable wsUrl, NSString* _Nullable keyJson, NSData* _Nullable header, NSData* _Nullable bz);

#endif
